# Data Handling with Python – Equifax cohort
1. Introduction to Data Handling with Python
```python
# Store this two-dimensional array
y = np.array([
    [12, 5, 2, 4],
    [ 7, 6, 8, 8],
    [ 1, 6, 7, 7]
])
```

In [3]:
import numpy as np
y = np.array([[12, 5, 2, 4], [ 7, 6, 8, 8], [ 1, 6, 7, 7]])

In [13]:
#1. Display the first 2 rows and the first 3 columns.
y[0:2,0:3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [14]:
#2. Display the first column of y.
y[:,0]

array([12,  7,  1])

In [15]:
#3. Display the first row of y.
y[0]
y[0,:]

array([12,  5,  2,  4])

In [11]:
#Read the contents of file cdc_1.csv, containing heights, weights and ages, into array data.
data = np.genfromtxt('data/cdc_1.csv', delimiter=',',skip_header=1)

In [12]:
data

array([[ 70., 175.,  77.],
       [ 71., 194.,  31.],
       [ 67., 170.,  45.],
       ...,
       [ 69., 224.,  73.],
       [ 73., 200.,  35.],
       [ 69., 170.,  83.]])

In [18]:
#4. Calculate the standard deviation and the mean for
#• height
#• weight
#• age
#Output the results in a printed summary

for i in np.arange(3):
    print(y[:,i].std())
    print(y[:,i].mean())

4.4969125210773475
6.666666666666667
0.4714045207910317
5.666666666666667
2.6246692913372702
5.666666666666667


In [19]:
#Extension - Next, read the contents of file cdc_nan.csv, containing heights, weights and ages, into array data. 
nan = np.genfromtxt('data/cdc_nan.csv', delimiter=',',skip_header=1)

In [24]:
#. Separate the heights (column 0) and the weights (column 1)
#2. Calculate the median for the heights and the weights and assign the values to variables.
#3. What has happened? Check if the arrays contain missing values.

heights = nan[:,0]
weights = nan[:,1]
median_height = np.median(heights)
median_weight = np.median(weights)

print(median_height)
print(median_weight)

70.0
nan


In [32]:
#4. Array weights contain three nan values. Find their positions.
np.argwhere(np.isnan(weights))

array([[ 3],
       [11],
       [17]])

In [31]:
#5. Now calculate the median for the weights ignoring the nan values.
np.median(weights[~np.isnan(weights)])

np.float64(185.0)