# Header
## Subheader
- list item
- another

In [1]:
import numpy as np

In [2]:
payments_list = [6.99, 12.40, 75.00, 1.55]
payments_list *2

[6.99, 12.4, 75.0, 1.55, 6.99, 12.4, 75.0, 1.55]

Broadcasting operations

In [8]:
pay_arr = np.array(payments_list)
transaction_fee = 1.5

(pay_arr * 1.2) + transaction_fee

array([ 9.888, 16.38 , 91.5  ,  3.36 ])

In [9]:
pay_arr >5

array([ True,  True,  True, False])

In [10]:
pay_arr[pay_arr >5]

array([ 6.99, 12.4 , 75.  ])

In [11]:
pay_arr[(pay_arr >5) & (pay_arr <50)]

array([ 6.99, 12.4 ])

In [12]:
pay_arr[2]

np.float64(75.0)

In [13]:
#slicing
pay_arr[0:2]

array([ 6.99, 12.4 ])

In [15]:
#cherry picking
pay_arr[[0,2]]

array([ 6.99, 75.  ])

In [17]:
#2 dimensional array
arr2 = np.array([[1,3,5,7],[2,4,6,8]])
arr2

array([[1, 3, 5, 7],
       [2, 4, 6, 8]])

In [18]:
arr2.reshape(4,2)

array([[1, 3],
       [5, 7],
       [2, 4],
       [6, 8]])

In [20]:
arr2.reshape(3,2)

ValueError: cannot reshape array of size 8 into shape (3,2)

In [21]:
np.arange(start=1, stop = 10, step = 3)
np.arange(1,10,3)

array([1, 4, 7])

In [30]:
#logical operators
np.all(pay_arr>50) # False
np.any(pay_arr>50) # True

np.True_

In [29]:
#descriptive statistics
pay_arr.sum()
pay_arr.min()
pay_arr.max()
pay_arr.mean()
pay_arr.var()
pay_arr.std()

np.float64(29.702279794655492)

In [32]:
#ufuncs - perform element wise operations
np.sqrt(pay_arr)
np.square(pay_arr)
np.exp(pay_arr)
np.log(pay_arr)
np.sign(pay_arr)
np.isnan(pay_arr)
np.sin(pay_arr)
np.add(pay_arr, pay_arr)

array([ 13.98,  24.8 , 150.  ,   3.1 ])

In [37]:
import os
os.getcwd()

'C:\\Users\\Admin\\Documents\\Course Files\\QADHPYTHON'